# Generated by Django 5.1.4 on 2024-12-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_tech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorvalue',
            name='value',
            field=models.FloatField(),
        ),
    ]
